export const UPDATE_LOGIN_FIELD = "UPDATE_LOGIN_FIELD";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";

export const UPDATE_REGISTER_FIELD = "UPDATE_REGISTER_FIELD";

export const UPDATE_ADMIN_PROPS = "UPDATE_ADMIN_PROPS";
export const DELETE_ADMIN_PROPS = "DELETE_ADMIN_PROPS";
export const MERGE_ADMIN_PROPS = "MERGE_ADMIN_PROPS";
